name: Expo Go Deployment
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy to Expo Go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo CLI
        run: npm install -g @expo/cli

      - name: Install dependencies
        run: npm ci

      - name: Login to Expo
        run: npx expo login -u pranjalekhande
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Publish to Expo Go
        run: npx expo export --platform all
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} 